[Feat] structure assignments controller
cs169/flextensions pull request #24
Opened 2024-03-15 03:14 UTC by Zzz212zzZ

# General Info

- [Pivotal Tracker Story](https://www.pivotaltracker.com/story/show/187205159)
- [ ] Breaking?

# Changes

Add three routes corresponding to our [design doc](https://docs.google.com/document/d/1iSImIhrJW1yXTubNW2nz5DAuGqB6HFF6f8eRw1SomoE/edit). GET, POST, DELETE.

# Testing

Add a `rspec` test skeleton for the three routes.
- `spec/controllers/api/v1/assignments_controller_spec.rb`

# Documentation

- `app/assets/swagger/swagger.json`

# Checklist

- [x] Name of branch corresponds to story

2024-03-18 22:49 UTC, Connor-Bernard requested changes

2024-03-18 22:49 UTC, Connor-Bernard commented on app/assets/swagger/swagger.json
> +        "summary": "Get all assignments from one (course,platform)",
```suggestion
        "summary": "Get all assignments from one (course, platform)",
```

2024-03-18 22:49 UTC, Connor-Bernard commented on app/assets/swagger/swagger.json
> +        "summary": "Create a new assignment from one (course,platform) on our side",
```suggestion
        "summary": "Create a new assignment from one (course, platform)",
```

2024-03-18 22:49 UTC, Connor-Bernard commented on app/assets/swagger/swagger.json
> +        "summary": "Delete an assignment from one (course,platform) on our side",
```suggestion
        "summary": "Delete an assignment from one (course, platform)",
```

2024-03-18 22:49 UTC, Connor-Bernard commented on spec/controllers/api/v1/assignments_controller_spec.rb
> +        RSpec.describe AssignmentsController, type: :controller do
```suggestion
        describe AssignmentsController, type: :controller do
```
Just to keep it consistent, though both do the same thing.

2024-03-18 22:49 UTC, Connor-Bernard commented on config/routes/api/v1.rb
These will have to be nested in the resources that they are pulling from the route, so we'll have to add those incrementally.

2024-04-01 04:40 UTC, Connor-Bernard approved these changes
LGTM

2024-04-11 00:10 UTC, Reimirno submitted a review, later dismissed

2024-04-11 00:47 UTC, Reimirno approved these changes

2024-04-11 00:50 UTC, merged

2024-04-16 01:19 UTC, Connor-Bernard reviewed
Should we be removing migrations or just re-migrating it to change what we need to?

2024-04-16 01:19 UTC, Connor-Bernard commented on config/database.yml
> -  username: <%= ENV['DB_USER'] || ENV['USER'] || 'postgres' %>
We need these configured because the different dbs will be configured with different creds

2024-04-16 01:19 UTC, Connor-Bernard commented on spec/controllers/api/v1/assignments_controller_spec.rb
The specs for other controller actions are pretty uniform.  This is fine technically, but just for consistency, it's probably best to refactor these tests to be in coordination with the other ones so people don't get confused later on down the line when they are looking at multiple different types of tests.