187434183 set up flow to create course
cs169/flextensions pull request #40
Opened 2024-04-22 17:39 UTC by cynthia-lixinyi

# General Info

- [Pivotal Tracker Story](https://www.pivotaltracker.com/story/show/########)
- [ ] Breaking?

# Changes

Explain your changes here (in such a way that you would understand why you made them a year from now).
Implemented `create` method in `class CoursesController`. This method intends to create an entry in the courses table.

# Testing

Explain how you tested your changes.  If testing is not necessary, explain why.
Two cases are tested:
(1) A course with the provided course_name is created successfully.
(2) A course with the same course name already exists. In this case, an error message saying "A course with the same course name already exists." shows up in the JSON response body

# Documentation

Does this PR require documentation.  If so, explain where it can be found.
N/A

# Checklist

- [x] Name of branch corresponds to story

2024-04-22 17:47 UTC, Connor-Bernard commented on app/controllers/api/v1/courses_controller.rb
> +      require 'lms_api'
What do we use this for?  I thought we were going to try to use the canvas facade

2024-04-22 17:48 UTC, Connor-Bernard commented on app/controllers/api/v1/courses_controller.rb
> +      require 'lms_api'
Also, how are we making the call to canvas?

2024-04-22 18:00 UTC, Connor-Bernard commented on app/views/courses/index.html.erb
Do we want to do any UI right now for the API?

2024-04-22 18:06 UTC, Connor-Bernard requested changes
Made a couple of comments

2024-04-23 20:41 UTC, cynthia-lixinyi reviewed
~~Looks good to me.~~ Sorry, my intention was to review another PR.

2024-04-23 22:27 UTC, Connor-Bernard approved these changes
LGTM

2024-04-23 22:44 UTC, merged